# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/azk/Desktop/COURSE_TRAINING/DOCKER_COURSE/C_DEV/code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/azk/Desktop/COURSE_TRAINING/DOCKER_COURSE/C_DEV/code

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/azk/Desktop/COURSE_TRAINING/DOCKER_COURSE/C_DEV/code/CMakeFiles /home/azk/Desktop/COURSE_TRAINING/DOCKER_COURSE/C_DEV/code//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/azk/Desktop/COURSE_TRAINING/DOCKER_COURSE/C_DEV/code/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GestionParking2

# Build rule for target.
GestionParking2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GestionParking2
.PHONY : GestionParking2

# fast build rule for target.
GestionParking2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/build
.PHONY : GestionParking2/fast

libs/sources/R/tauxOccupation.o: libs/sources/R/tauxOccupation.c.o

.PHONY : libs/sources/R/tauxOccupation.o

# target to build an object file
libs/sources/R/tauxOccupation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/R/tauxOccupation.c.o
.PHONY : libs/sources/R/tauxOccupation.c.o

libs/sources/R/tauxOccupation.i: libs/sources/R/tauxOccupation.c.i

.PHONY : libs/sources/R/tauxOccupation.i

# target to preprocess a source file
libs/sources/R/tauxOccupation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/R/tauxOccupation.c.i
.PHONY : libs/sources/R/tauxOccupation.c.i

libs/sources/R/tauxOccupation.s: libs/sources/R/tauxOccupation.c.s

.PHONY : libs/sources/R/tauxOccupation.s

# target to generate assembly for a file
libs/sources/R/tauxOccupation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/R/tauxOccupation.c.s
.PHONY : libs/sources/R/tauxOccupation.c.s

libs/sources/dbConnect.o: libs/sources/dbConnect.c.o

.PHONY : libs/sources/dbConnect.o

# target to build an object file
libs/sources/dbConnect.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/dbConnect.c.o
.PHONY : libs/sources/dbConnect.c.o

libs/sources/dbConnect.i: libs/sources/dbConnect.c.i

.PHONY : libs/sources/dbConnect.i

# target to preprocess a source file
libs/sources/dbConnect.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/dbConnect.c.i
.PHONY : libs/sources/dbConnect.c.i

libs/sources/dbConnect.s: libs/sources/dbConnect.c.s

.PHONY : libs/sources/dbConnect.s

# target to generate assembly for a file
libs/sources/dbConnect.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/dbConnect.c.s
.PHONY : libs/sources/dbConnect.c.s

libs/sources/menu.o: libs/sources/menu.c.o

.PHONY : libs/sources/menu.o

# target to build an object file
libs/sources/menu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/menu.c.o
.PHONY : libs/sources/menu.c.o

libs/sources/menu.i: libs/sources/menu.c.i

.PHONY : libs/sources/menu.i

# target to preprocess a source file
libs/sources/menu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/menu.c.i
.PHONY : libs/sources/menu.c.i

libs/sources/menu.s: libs/sources/menu.c.s

.PHONY : libs/sources/menu.s

# target to generate assembly for a file
libs/sources/menu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/menu.c.s
.PHONY : libs/sources/menu.c.s

libs/sources/type_vehicule/afficherNombrePlacesDisponibles.o: libs/sources/type_vehicule/afficherNombrePlacesDisponibles.c.o

.PHONY : libs/sources/type_vehicule/afficherNombrePlacesDisponibles.o

# target to build an object file
libs/sources/type_vehicule/afficherNombrePlacesDisponibles.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/type_vehicule/afficherNombrePlacesDisponibles.c.o
.PHONY : libs/sources/type_vehicule/afficherNombrePlacesDisponibles.c.o

libs/sources/type_vehicule/afficherNombrePlacesDisponibles.i: libs/sources/type_vehicule/afficherNombrePlacesDisponibles.c.i

.PHONY : libs/sources/type_vehicule/afficherNombrePlacesDisponibles.i

# target to preprocess a source file
libs/sources/type_vehicule/afficherNombrePlacesDisponibles.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/type_vehicule/afficherNombrePlacesDisponibles.c.i
.PHONY : libs/sources/type_vehicule/afficherNombrePlacesDisponibles.c.i

libs/sources/type_vehicule/afficherNombrePlacesDisponibles.s: libs/sources/type_vehicule/afficherNombrePlacesDisponibles.c.s

.PHONY : libs/sources/type_vehicule/afficherNombrePlacesDisponibles.s

# target to generate assembly for a file
libs/sources/type_vehicule/afficherNombrePlacesDisponibles.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/type_vehicule/afficherNombrePlacesDisponibles.c.s
.PHONY : libs/sources/type_vehicule/afficherNombrePlacesDisponibles.c.s

libs/sources/type_vehicule/identifierTypeVehicule.o: libs/sources/type_vehicule/identifierTypeVehicule.c.o

.PHONY : libs/sources/type_vehicule/identifierTypeVehicule.o

# target to build an object file
libs/sources/type_vehicule/identifierTypeVehicule.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/type_vehicule/identifierTypeVehicule.c.o
.PHONY : libs/sources/type_vehicule/identifierTypeVehicule.c.o

libs/sources/type_vehicule/identifierTypeVehicule.i: libs/sources/type_vehicule/identifierTypeVehicule.c.i

.PHONY : libs/sources/type_vehicule/identifierTypeVehicule.i

# target to preprocess a source file
libs/sources/type_vehicule/identifierTypeVehicule.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/type_vehicule/identifierTypeVehicule.c.i
.PHONY : libs/sources/type_vehicule/identifierTypeVehicule.c.i

libs/sources/type_vehicule/identifierTypeVehicule.s: libs/sources/type_vehicule/identifierTypeVehicule.c.s

.PHONY : libs/sources/type_vehicule/identifierTypeVehicule.s

# target to generate assembly for a file
libs/sources/type_vehicule/identifierTypeVehicule.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/type_vehicule/identifierTypeVehicule.c.s
.PHONY : libs/sources/type_vehicule/identifierTypeVehicule.c.s

libs/sources/type_vehicule/libererPlaceParking.o: libs/sources/type_vehicule/libererPlaceParking.c.o

.PHONY : libs/sources/type_vehicule/libererPlaceParking.o

# target to build an object file
libs/sources/type_vehicule/libererPlaceParking.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/type_vehicule/libererPlaceParking.c.o
.PHONY : libs/sources/type_vehicule/libererPlaceParking.c.o

libs/sources/type_vehicule/libererPlaceParking.i: libs/sources/type_vehicule/libererPlaceParking.c.i

.PHONY : libs/sources/type_vehicule/libererPlaceParking.i

# target to preprocess a source file
libs/sources/type_vehicule/libererPlaceParking.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/type_vehicule/libererPlaceParking.c.i
.PHONY : libs/sources/type_vehicule/libererPlaceParking.c.i

libs/sources/type_vehicule/libererPlaceParking.s: libs/sources/type_vehicule/libererPlaceParking.c.s

.PHONY : libs/sources/type_vehicule/libererPlaceParking.s

# target to generate assembly for a file
libs/sources/type_vehicule/libererPlaceParking.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/type_vehicule/libererPlaceParking.c.s
.PHONY : libs/sources/type_vehicule/libererPlaceParking.c.s

libs/sources/type_vehicule/nombreDePlacesDisponibles.o: libs/sources/type_vehicule/nombreDePlacesDisponibles.c.o

.PHONY : libs/sources/type_vehicule/nombreDePlacesDisponibles.o

# target to build an object file
libs/sources/type_vehicule/nombreDePlacesDisponibles.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/type_vehicule/nombreDePlacesDisponibles.c.o
.PHONY : libs/sources/type_vehicule/nombreDePlacesDisponibles.c.o

libs/sources/type_vehicule/nombreDePlacesDisponibles.i: libs/sources/type_vehicule/nombreDePlacesDisponibles.c.i

.PHONY : libs/sources/type_vehicule/nombreDePlacesDisponibles.i

# target to preprocess a source file
libs/sources/type_vehicule/nombreDePlacesDisponibles.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/type_vehicule/nombreDePlacesDisponibles.c.i
.PHONY : libs/sources/type_vehicule/nombreDePlacesDisponibles.c.i

libs/sources/type_vehicule/nombreDePlacesDisponibles.s: libs/sources/type_vehicule/nombreDePlacesDisponibles.c.s

.PHONY : libs/sources/type_vehicule/nombreDePlacesDisponibles.s

# target to generate assembly for a file
libs/sources/type_vehicule/nombreDePlacesDisponibles.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/type_vehicule/nombreDePlacesDisponibles.c.s
.PHONY : libs/sources/type_vehicule/nombreDePlacesDisponibles.c.s

libs/sources/type_vehicule/recupListeTypeVehicule.o: libs/sources/type_vehicule/recupListeTypeVehicule.c.o

.PHONY : libs/sources/type_vehicule/recupListeTypeVehicule.o

# target to build an object file
libs/sources/type_vehicule/recupListeTypeVehicule.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/type_vehicule/recupListeTypeVehicule.c.o
.PHONY : libs/sources/type_vehicule/recupListeTypeVehicule.c.o

libs/sources/type_vehicule/recupListeTypeVehicule.i: libs/sources/type_vehicule/recupListeTypeVehicule.c.i

.PHONY : libs/sources/type_vehicule/recupListeTypeVehicule.i

# target to preprocess a source file
libs/sources/type_vehicule/recupListeTypeVehicule.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/type_vehicule/recupListeTypeVehicule.c.i
.PHONY : libs/sources/type_vehicule/recupListeTypeVehicule.c.i

libs/sources/type_vehicule/recupListeTypeVehicule.s: libs/sources/type_vehicule/recupListeTypeVehicule.c.s

.PHONY : libs/sources/type_vehicule/recupListeTypeVehicule.s

# target to generate assembly for a file
libs/sources/type_vehicule/recupListeTypeVehicule.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/type_vehicule/recupListeTypeVehicule.c.s
.PHONY : libs/sources/type_vehicule/recupListeTypeVehicule.c.s

libs/sources/vehicule/calculPrixParking.o: libs/sources/vehicule/calculPrixParking.c.o

.PHONY : libs/sources/vehicule/calculPrixParking.o

# target to build an object file
libs/sources/vehicule/calculPrixParking.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/vehicule/calculPrixParking.c.o
.PHONY : libs/sources/vehicule/calculPrixParking.c.o

libs/sources/vehicule/calculPrixParking.i: libs/sources/vehicule/calculPrixParking.c.i

.PHONY : libs/sources/vehicule/calculPrixParking.i

# target to preprocess a source file
libs/sources/vehicule/calculPrixParking.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/vehicule/calculPrixParking.c.i
.PHONY : libs/sources/vehicule/calculPrixParking.c.i

libs/sources/vehicule/calculPrixParking.s: libs/sources/vehicule/calculPrixParking.c.s

.PHONY : libs/sources/vehicule/calculPrixParking.s

# target to generate assembly for a file
libs/sources/vehicule/calculPrixParking.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/vehicule/calculPrixParking.c.s
.PHONY : libs/sources/vehicule/calculPrixParking.c.s

libs/sources/vehicule/entreeNouveauVehicule.o: libs/sources/vehicule/entreeNouveauVehicule.c.o

.PHONY : libs/sources/vehicule/entreeNouveauVehicule.o

# target to build an object file
libs/sources/vehicule/entreeNouveauVehicule.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/vehicule/entreeNouveauVehicule.c.o
.PHONY : libs/sources/vehicule/entreeNouveauVehicule.c.o

libs/sources/vehicule/entreeNouveauVehicule.i: libs/sources/vehicule/entreeNouveauVehicule.c.i

.PHONY : libs/sources/vehicule/entreeNouveauVehicule.i

# target to preprocess a source file
libs/sources/vehicule/entreeNouveauVehicule.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/vehicule/entreeNouveauVehicule.c.i
.PHONY : libs/sources/vehicule/entreeNouveauVehicule.c.i

libs/sources/vehicule/entreeNouveauVehicule.s: libs/sources/vehicule/entreeNouveauVehicule.c.s

.PHONY : libs/sources/vehicule/entreeNouveauVehicule.s

# target to generate assembly for a file
libs/sources/vehicule/entreeNouveauVehicule.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/vehicule/entreeNouveauVehicule.c.s
.PHONY : libs/sources/vehicule/entreeNouveauVehicule.c.s

libs/sources/vehicule/facturerVehicule.o: libs/sources/vehicule/facturerVehicule.c.o

.PHONY : libs/sources/vehicule/facturerVehicule.o

# target to build an object file
libs/sources/vehicule/facturerVehicule.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/vehicule/facturerVehicule.c.o
.PHONY : libs/sources/vehicule/facturerVehicule.c.o

libs/sources/vehicule/facturerVehicule.i: libs/sources/vehicule/facturerVehicule.c.i

.PHONY : libs/sources/vehicule/facturerVehicule.i

# target to preprocess a source file
libs/sources/vehicule/facturerVehicule.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/vehicule/facturerVehicule.c.i
.PHONY : libs/sources/vehicule/facturerVehicule.c.i

libs/sources/vehicule/facturerVehicule.s: libs/sources/vehicule/facturerVehicule.c.s

.PHONY : libs/sources/vehicule/facturerVehicule.s

# target to generate assembly for a file
libs/sources/vehicule/facturerVehicule.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/vehicule/facturerVehicule.c.s
.PHONY : libs/sources/vehicule/facturerVehicule.c.s

libs/sources/vehicule/retrouverVehicule.o: libs/sources/vehicule/retrouverVehicule.c.o

.PHONY : libs/sources/vehicule/retrouverVehicule.o

# target to build an object file
libs/sources/vehicule/retrouverVehicule.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/vehicule/retrouverVehicule.c.o
.PHONY : libs/sources/vehicule/retrouverVehicule.c.o

libs/sources/vehicule/retrouverVehicule.i: libs/sources/vehicule/retrouverVehicule.c.i

.PHONY : libs/sources/vehicule/retrouverVehicule.i

# target to preprocess a source file
libs/sources/vehicule/retrouverVehicule.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/vehicule/retrouverVehicule.c.i
.PHONY : libs/sources/vehicule/retrouverVehicule.c.i

libs/sources/vehicule/retrouverVehicule.s: libs/sources/vehicule/retrouverVehicule.c.s

.PHONY : libs/sources/vehicule/retrouverVehicule.s

# target to generate assembly for a file
libs/sources/vehicule/retrouverVehicule.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/vehicule/retrouverVehicule.c.s
.PHONY : libs/sources/vehicule/retrouverVehicule.c.s

libs/sources/vehicule/sortirVehicule.o: libs/sources/vehicule/sortirVehicule.c.o

.PHONY : libs/sources/vehicule/sortirVehicule.o

# target to build an object file
libs/sources/vehicule/sortirVehicule.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/vehicule/sortirVehicule.c.o
.PHONY : libs/sources/vehicule/sortirVehicule.c.o

libs/sources/vehicule/sortirVehicule.i: libs/sources/vehicule/sortirVehicule.c.i

.PHONY : libs/sources/vehicule/sortirVehicule.i

# target to preprocess a source file
libs/sources/vehicule/sortirVehicule.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/vehicule/sortirVehicule.c.i
.PHONY : libs/sources/vehicule/sortirVehicule.c.i

libs/sources/vehicule/sortirVehicule.s: libs/sources/vehicule/sortirVehicule.c.s

.PHONY : libs/sources/vehicule/sortirVehicule.s

# target to generate assembly for a file
libs/sources/vehicule/sortirVehicule.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/libs/sources/vehicule/sortirVehicule.c.s
.PHONY : libs/sources/vehicule/sortirVehicule.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GestionParking2.dir/build.make CMakeFiles/GestionParking2.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GestionParking2"
	@echo "... libs/sources/R/tauxOccupation.o"
	@echo "... libs/sources/R/tauxOccupation.i"
	@echo "... libs/sources/R/tauxOccupation.s"
	@echo "... libs/sources/dbConnect.o"
	@echo "... libs/sources/dbConnect.i"
	@echo "... libs/sources/dbConnect.s"
	@echo "... libs/sources/menu.o"
	@echo "... libs/sources/menu.i"
	@echo "... libs/sources/menu.s"
	@echo "... libs/sources/type_vehicule/afficherNombrePlacesDisponibles.o"
	@echo "... libs/sources/type_vehicule/afficherNombrePlacesDisponibles.i"
	@echo "... libs/sources/type_vehicule/afficherNombrePlacesDisponibles.s"
	@echo "... libs/sources/type_vehicule/identifierTypeVehicule.o"
	@echo "... libs/sources/type_vehicule/identifierTypeVehicule.i"
	@echo "... libs/sources/type_vehicule/identifierTypeVehicule.s"
	@echo "... libs/sources/type_vehicule/libererPlaceParking.o"
	@echo "... libs/sources/type_vehicule/libererPlaceParking.i"
	@echo "... libs/sources/type_vehicule/libererPlaceParking.s"
	@echo "... libs/sources/type_vehicule/nombreDePlacesDisponibles.o"
	@echo "... libs/sources/type_vehicule/nombreDePlacesDisponibles.i"
	@echo "... libs/sources/type_vehicule/nombreDePlacesDisponibles.s"
	@echo "... libs/sources/type_vehicule/recupListeTypeVehicule.o"
	@echo "... libs/sources/type_vehicule/recupListeTypeVehicule.i"
	@echo "... libs/sources/type_vehicule/recupListeTypeVehicule.s"
	@echo "... libs/sources/vehicule/calculPrixParking.o"
	@echo "... libs/sources/vehicule/calculPrixParking.i"
	@echo "... libs/sources/vehicule/calculPrixParking.s"
	@echo "... libs/sources/vehicule/entreeNouveauVehicule.o"
	@echo "... libs/sources/vehicule/entreeNouveauVehicule.i"
	@echo "... libs/sources/vehicule/entreeNouveauVehicule.s"
	@echo "... libs/sources/vehicule/facturerVehicule.o"
	@echo "... libs/sources/vehicule/facturerVehicule.i"
	@echo "... libs/sources/vehicule/facturerVehicule.s"
	@echo "... libs/sources/vehicule/retrouverVehicule.o"
	@echo "... libs/sources/vehicule/retrouverVehicule.i"
	@echo "... libs/sources/vehicule/retrouverVehicule.s"
	@echo "... libs/sources/vehicule/sortirVehicule.o"
	@echo "... libs/sources/vehicule/sortirVehicule.i"
	@echo "... libs/sources/vehicule/sortirVehicule.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

